export interface MenuItem {
  name: string;
  price: number;
}

export interface MenuCategory {
  [category: string]: MenuItem[];
}

export const MENU: MenuCategory = {
  Protein: [
    { name: "Pepper Chicken", price: 2000 },
    { name: "Fried Hake Fish", price: 2000 },
    { name: "Goat in Stew", price: 2800 },
    { name: "Beef in Stew / Assorted Beef", price: 1200 },
    { name: "Boiled Egg", price: 500 },
    { name: "Sausage", price: 1000 },
    { name: "Fried Mackerel", price: 2000 },
    { name: "Croacker Fish", price: 2000 },
    { name: "Fried Catfish", price: 2000 },
    { name: "Ponmo", price: 800 },
    { name: "Turkey (large/medium)", price: 2500 },
    { name: "Ponmo Sauce", price: 1500 },
    { name: "Gizdodo", price: 2500 },
    { name: "Asun", price: 2500 },
    { name: "Cowtail", price: 2000 },
    { name: "Cowleg", price: 2000 },
    { name: "Pepper Soup", price: 3500 },
  ],
  "Main Dish": [
    { name: "Jollof Rice (per scoop)", price: 700 },
    { name: "Stir Fry Spaghetti (per scoop)", price: 900 },
    { name: "Ewa Agoyin (per scoop)", price: 800 },
    { name: "Fried Rice (per scoop)", price: 1000 },
    { name: "Dirty Rice", price: 1500 },
    { name: "Asun Pasta", price: 1500 },
    { name: "Asun Rice", price: 1500 },
    { name: "Coconut Rice", price: 1200 },
    { name: "Concoction Rice", price: 1200 },
    { name: "White Rice", price: 500 },
    { name: "Village Rice", price: 1500 },
    { name: "Village Pasta", price: 1500 },
    { name: "Ofada Rice", price: 800 },
    { name: "Beans Pottage", price: 900 },
    { name: "Plantain Pottage", price: 1500 },
    { name: "Fried Beans", price: 1500 },
    { name: "Rice and Bean", price: 800 },
    { name: "Caribbean Rice and Peas", price: 1200 },
    { name: "Fried Sweet Potato (4 pcs)", price: 750 },
    { name: "Yamarita (per one)", price: 900 },
    { name: "Burger", price: 4000 },
    { name: "Club Sandwich", price: 4000 },
    { name: "Yam (per piece)", price: 700 },
  ],
  Swallow: [
    { name: "Poundo Yam", price: 700 },
    { name: "Eba (Garri)", price: 700 },
    { name: "Semo", price: 700 },
    { name: "Wheat", price: 700 },
    { name: "Fufu", price: 500 },
    { name: "Amala", price: 500 },
    { name: "Eko", price: 500 },
    { name: "Starch", price: 700 },
  ],
  Soups: [
    { name: "Egusi", price: 1500 },
    { name: "Eforiro", price: 1500 },
    { name: "Ila Alsepo", price: 1500 },
    { name: "Seafood Okro", price: 5500 },
    { name: "Fisherman Soup", price: 7000 },
    { name: "Edikankong", price: 1500 },
    { name: "Afang", price: 1500 },
    { name: "Banga", price: 15000 },
    { name: "White Soup", price: 2000 },
    { name: "Blacksoup", price: 1500 },
    { name: "Oha Soup", price: 2000 },
    { name: "Ogbono", price: 2000 },
    { name: "Egusi Peppersoup", price: 1500 },
    { name: "Ewedu", price: 700 },
    { name: "Gbegiri", price: 700 },
    { name: "Bitterleaf Soup", price: 1500 },
    { name: "Groundnut Soup", price: 2000 },
  ],
  Accompaniment: [
    { name: "Plantain", price: 1000 },
    { name: "Salad", price: 2500 },
    { name: "Moi Moi", price: 800 },
    { name: "Cole Slaw", price: 1000 },
  ],
  Snacks: [
    { name: "Small Chops", price: 250 },
    { name: "Meat Pie", price: 1900 },
    { name: "Sausage Roll", price: 800 },
    { name: "Scotch Egg", price: 800 },
    { name: "Donut", price: 700 },
    { name: "Frank Roll", price: 900 },
    { name: "Fish Pie", price: 900 },
    { name: "Chicken Pie", price: 1200 },
  ],
  Sauce: [
    { name: "Fish Sauce", price: 2000 },
    { name: "Ofada Sauce", price: 2500 },
    { name: "Egg Sauce", price: 1700 },
    { name: "Cornbeef Sauce", price: 2000 },
    { name: "Vicky's Pepper Sauce", price: 2500 },
  ],
};

export const MENU_CATEGORIES = Object.keys(MENU);
